In [1]:
import numpy as np

Lista vs Array

In [1]:
lista = [2,3,5, "Hola"]
print(lista)

[2, 3, 5, 'Hola']


In [3]:
#el array es una matriz atraves de una lista precisamente una lista de listas
matriz = [[1,2,3],
          [4,5,6],    
          [7,8,9]]
print(matriz[1][2])  #para llamar al 6 - fila 1 columna 2

6


In [7]:
#crear un arrays
numeros = [3,4,5,6]
a = np.array(numeros)
a[2:]

array([5, 6])

In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [2]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [3]:
b.ndim

2